[project]
name = "scripts"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi>=0.117.1",
    "modal>=1.1.4",
    "openai>=1.109.1",
    "transformers>=4.56.2",
]
